### ISSUE TITLE
Issue with persistentVolume

### ISSUE THREAD

**Issue by ank-ankur** [sj14/helm-charts#75]
Hello, 

I am using chart version 0.7.0 and While using "persistentVolume" option, i get a problem of "permission denied" when sftp user tried to make an upload.

Background:
I am trying to run this in GKE backed by a bucket as persistent volume. This is the block from helm i am using 
```
  sftp:
    users:
      - name: user1
        pass: user1
        dirs:
          - dir1

  persistentVolume:
    enabled: true
    accessModes: 
      - ReadWriteMany
    size: 40Gi
    storageClass: cs-fuse-sftp
    subPath: data
```
This results in following structure in bucket "data/user1/dir1". But when this user tried to upload file, it fails for "Permission denied"

The GKE container shows "root" permissions and would not allow any write permissions.
```
sftp-gw-atmoz-sftp-server-6bc7c7b9db-t8zdp:/home# ls -l
total 0
drwxr-xr-x    1 root     root             0 Feb 26 14:05 user1
drwxr-xr-x    1 root     root             0 Feb 26 14:05 user2
sftp-gw-atmoz-sftp-server-6bc7c7b9db-t8zdp:/home/user1# ls -l
total 0
drwxr-xr-x    1 root     root             0 Feb 26 14:05 dir1
```

If i do not enable "persistentVolume", then it works and "dir1" will get permission of "user1" as owner and write operation works.

Is there anything that i am missing or misconfigured? how can user can retain permission on sub folders.

Would appreciate any suggestions/pointers 

Ankur
